export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_EMAILCONFIRMED = 'AUTH_EMAILCONFIRMED';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const SET_COUNTRYMASTERDATA = 'SET_COUNTRYMASTERDATA';
export const SET_ENTITYTYPEMASTERDATA = 'SET_ENTITYTYPEMASTERDATA';
export const SET_INDUSTRYMASTERDATA = 'SET_INDUSTRYMASTERDATA';
export const FETCH_MASTERDATA_FAILED = 'FETCH_MASTERDATA_FAILED';


export const FETCHPROFILE1_START ="FETCHPROFILE1_START";
export const FETCHPROFILE1_SUCCESS ="FETCHPROFILE1_SUCCESS";
export const FETCHPROFILE1_FAIL ="FETCHPROFILE1_FAIL";


export const FETCHPROFILE2_START ="FETCHPROFILE2_START";
export const FETCHPROFILE2_SUCCESS ="FETCHPROFILE2_SUCCESS";
export const FETCHPROFILE2_FAIL ="FETCHPROFILE2_FAIL";


export const FETCHPROFILE3_START ="FETCHPROFILE3_START";
export const FETCHPROFILE3_SUCCESS ="FETCHPROFILE3_SUCCESS";
export const FETCHPROFILE3_FAIL ="FETCHPROFILE3_FAIL";

export const PROFILE1_START ="PROFILE1_START";
export const PROFILE1_SUCCESS ="PROFILE1_SUCCESS";
export const PROFILE1_FAIL ="PROFILE1_FAIL";

export const PROFILE2_START ="PROFILE2_START";
export const PROFILE2_SUCCESS ="PROFILE2_SUCCESS";
export const PROFILE2_FAIL ="PROFILE2_FAIL";

export const PROFILE3_START ="PROFILE3_START";
export const PROFILE3_SUCCESS ="PROFILE3_SUCCESS";
export const PROFILE3_FAIL ="PROFILE3_FAIL";



export const MODERATORDETAIL_START ="MODERATORDETAIL_START";
export const MODERATORDETAIL_SUCCESS ="MODERATORDETAIL_SUCCESS";
export const MODERATORDETAIL_FAIL ="MODERATORDETAIL_FAIL";

export const MODERATORBANKDETAIL_START ="MODERATORBANKDETAIL_START";
export const MODERATORBANKDETAIL_SUCCESS ="MODERATORBANKDETAIL_SUCCESS";
export const MODERATORBANKDETAIL_FAIL ="MODERATORBANKDETAIL_FAIL";

export const MODERATORDOCDETAIL_START ="MODERATORDOCDETAIL_START";
export const MODERATORDOCDETAIL_SUCCESS ="MODERATORDOCDETAIL_SUCCESS";
export const MODERATORDOCDETAIL_FAIL ="MODERATORDOCDETAIL_FAIL";


export const WINGSCREATE_START ="WINGSCREATE_START";
export const WINGSCREATE_SUCCESS ="WINGSCREATE_SUCCESS";
export const WINGSCREATE_FAIL ="WINGSCREATE_FAIL";


export const ABOUTME_START ="ABOUTME_START";
export const ABOUTME_SUCCESS ="ABOUTME_SUCCESS";
export const ABOUTME_FAIL ="ABOUTME_FAIL";

export const WINGNAME_START ="WINGNAME_START";
export const WINGNAME_SUCCESS ="WINGNAME_SUCCESS";
export const WINGNAME_FAIL ="WINGNAME_FAIL";

export const DESIGNATIONLOCATION_START ="DESIGNATIONLOCATION_START";
export const DESIGNATIONLOCATION_SUCCESS ="DESIGNATIONLOCATION_SUCCESS";
export const DESIGNATIONLOCATION_FAIL ="DESIGNATIONLOCATION_FAIL";

export const COVERIMAGE_START ="COVERIMAGE_START";
export const COVERIMAGE_SUCCESS ="COVERIMAGE_SUCCESS";
export const COVERIMAGE_FAIL ="COVERIMAGE_FAIL";


export const PROFILEIMAGE_START ="PROFILEIMAGE_START";
export const PROFILEIMAGE_SUCCESS ="PROFILEIMAGE_SUCCESS";
export const PROFILEIMAGE_FAIL ="PROFILEIMAGE_FAIL";


export const SAVE_EDUCATION_START ="SAVE_EDUCATION_START";
export const SAVE_EDUCATION_SUCCESS ="SAVE_EDUCATION_SUCCESS";
export const SAVE_EDUCATION_FAIL ="SAVE_EDUCATION_FAIL";

export const UPDATE_EDUCATION_START ="UPDATE_EDUCATION_START";
export const UPDATE_EDUCATION_SUCCESS ="UPDATE_EDUCATION_SUCCESS";
export const UPDATE_EDUCATION_FAIL ="UPDATE_EDUCATION_FAIL";

export const DELETE_EDUCATION_START ="DELETE_EDUCATION_START";
export const DELETE_EDUCATION_SUCCESS ="DELETE_EDUCATION_SUCCESS";
export const DELETE_EDUCATION_FAIL ="DELETE_EDUCATION_FAIL";



export const SAVE_WORKEXP_START ="SAVE_WORKEXP_START";
export const SAVE_WORKEXP_SUCCESS ="SAVE_WORKEXP_SUCCESS";
export const SAVE_WORKEXP_FAIL ="SAVE_WORKEXP_FAIL";



export const DELETE_WORKEXP_START ="DELETE_WORKEXP_START";
export const DELETE_WORKEXP_SUCCESS ="DELETE_WORKEXP_SUCCESS";
export const DELETE_WORKEXP_FAIL ="DELETE_WORKEXP_FAIL";



export const USER_POST_START ="USER_POST_START";
export const USER_POST_SUCCESS ="USER_POST_SUCCESS";
export const USER_POST_FAIL ="USER_POST_FAIL";


export const USER_POSTUPDATE_START ="USER_POSTUPDATE_START";
export const USER_POSTUPDATE_SUCCESS ="USER_POSTUPDATE_SUCCESS";
export const USER_POSTUPDATE_FAIL ="USER_POSTUPDATE_FAIL";


export const USER_POSTDELETE_START ="USER_POSTDELETE_START";
export const USER_POSTDELETE_SUCCESS ="USER_POSTDELETE_SUCCESS";
export const USER_POSTDELETE_FAIL ="USER_POSTDELETE_FAIL";







export const USER_LIKES_START ="USER_LIKES_START";
export const USER_LIKES_SUCCESS ="USER_LIKES_SUCCESS";
export const USER_LIKES_FAIL ="USER_LIKES_FAIL";

export const USER_UNLIKES_START ="USER_UNLIKES_START";
export const USER_UNLIKES_SUCCESS ="USER_UNLIKES_SUCCESS";
export const USER_UNLIKES_FAIL ="USER_UNLIKES_FAIL";


export const USER_COMMENTS_START ="USER_COMMENTS_START";
export const USER_COMMENTS_SUCCESS ="USER_COMMENTS_SUCCESS";
export const USER_COMMENTS_FAIL ="USER_COMMENTS_FAIL";


export const USER_NOTIFICATIONMARKASSEEN_START ="USER_NOTIFICATIONMARKASSEEN_START";
export const USER_NOTIFICATIONMARKASSEEN_SUCCESS ="USER_NOTIFICATIONMARKASSEEN_SUCCESS";
export const USER_NOTIFICATIONMARKASSEEN_FAIL ="USER_NOTIFICATIONMARKASSEEN_FAIL";


export const USER_FEEDPOSTREPORT_START ="USER_FEEDPOSTREPORT_START";
export const USER_FEEDPOSTREPORT_SUCCESS ="USER_FEEDPOSTREPORT_SUCCESS";
export const USER_FEEDPOSTREPORT_FAIL ="USER_FEEDPOSTREPORT_FAIL";



export const EXHIBITION_ENQUIRIES_START ="EXHIBITION_ENQUIRIES_START";
export const EXHIBITION_ENQUIRIES_SUCCESS ="EXHIBITION_ENQUIRIES_SUCCESS";
export const EXHIBITION_ENQUIRIES_FAIL ="EXHIBITION_ENQUIRIES_FAIL";


